[build]
  command = "yarn build"
  functions = "proxy/lambda-build"
  publish = "app/build"

[dev]
  functionsPort = 34567 # port for functions server

[[redirects]]
  from = "/*"
  to = "https://www.baileyhikawa.com/:splat"
  status = 301
